FROM node:22-alpine AS build

WORKDIR /app
RUN npm install --global yarn@1.22.22

COPY package.json yarn.lock ./
RUN yarn install --non-interactive --network-timeout 100000

COPY . .
ARG REACT_APP_BACKEND_URL=
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
RUN yarn build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
